config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get "/:locale" => "pages#home"
    root to: "pages#home"

    get "about", to: "pages#about"
    resources :partners, only: %i[index]
    resources :projects, only: %i[index show]
    resources :messages, only: %i[new create]
  end

  namespace :admin do
    root to: "projects#index"

    resources :pages, only: %i[index edit] do
      resources :text_block, only: [] do
        member do
          patch :update_text_block, controller: "pages"
        end
      end
    end
    resources :project_categories, only: %i[index edit update] do
      member do
        get :update_position
      end
    end
    resources :projects, only: %i[index new create show edit update destroy] do
      resources :container_blocks, only: %i[create update destroy] do
        member do
          get :update_position
        end
        resources :content_blocks, only: [] do
          resources :text_blocks, only: %i[create update destroy]
          resources :image_blocks, only: %i[create update destroy]
          member do
            get :update_position
          end
        end
      end
    end
    resources :team_members, only: %i[index new create edit update destroy]
    resources :partners, only: %i[index new create edit update destroy]
    resources :messages, only: %i[index show destroy]
    resources :users, only: %i[index edit update]
  end
end

app/views/admin/pages/edit.html.erb
<header class="flex justify-between items-center mb-6">
  <h1 class="text-3xl font-bold mb-4"><%= t("edit_texts") %> | <%= t(@page.name.downcase) %></h1>
</header>
<div class="flex flex-col gap-10">
  <% @page.container_blocks.each do |container_block| %>
    <% text_block = container_block.content_blocks.first.text_block %>
    <section class="bg-white p-4">
      <%=
        form_with model: [:update_text_block_admin, @page, text_block],
        class: "flex flex-col gap-4",
        data: { controller: "text-block-form"} do |form|
      %>
        <div class="flex justify-between items-center">
          <h2 class="text-xl font-bold mb-4"><%= container_block.location&.humanize %></h2>
          <%= form.checkbox :is_raw_html, class: "hidden peer", data: { action: "change->text-block-form#isRawHtmlChanged"} %>
          <%= form.label :is_raw_html, "HTML", class: "px-3 py-2 text-gray-500 cursor-pointer transition-colors hover:text-black peer-checked:bg-black peer-checked:text-white" %>
        </div>
        <div>
          <%= form.label :text, "#{t('text')} FR" %>
          <div class="has-[trix-editor:disabled]:hidden">
            <%=
              form.rich_textarea :text,
              id: form.object.object_id,
              disabled: text_block.is_raw_html?,
              data: { "text-block-form-target": "richTextEditor" }
            %>
          </div>
          <%=
            form.textarea :text,
            value: text_block.text.body&.html_safe,
            rows: 4,
            disabled: !text_block.is_raw_html?,
            class: "border w-full disabled:hidden",
            data: { "text-block-form-target": "rawTextInput" }
          %>
        </div>
        <div>
          <%= form.label :text_en, "#{t('text')} EN" %>
          <div class="has-[trix-editor:disabled]:hidden">
            <%=
              form.rich_textarea :text_en,
              id: "#{form.object.object_id}-en",
              disabled: text_block.is_raw_html?,
              data: { "text-block-form-target": "richTextEditor" }
            %>
          </div>
          <%=
            form.textarea :text_en,
            value: text_block.text_en.body&.html_safe,
            rows: 4,
            disabled: !text_block.is_raw_html?,
            class: "border w-full disabled:hidden",
            data: { "text-block-form-target": "rawTextInput" }
          %>
        </div>
        <%= form.submit t("save"), class: "admin-btn-primary cursor-pointer", data: { action: "click->modal#closeModal" } %>
      <% end %>
    </section>
  <% end %>
</div>

app/views/admin/pages/index.html.erb
<header class="flex justify-between items-center mb-6">
  <h1 class="text-3xl font-bold mb-4"><%= t("pages") %></h1>
</header>
<div class="flex flex-col gap-4">
  <% @pages.each do |page| %>
    <div class="flex gap-4 items-center justify-between bg-white p-4 border">
      <h2 class="text-xl font-bold"><%= page.name %></h2>
      <div class="flex flex-col gap-4">
        <%= link_to t("edit_texts"), edit_admin_page_path(page), class: "admin-btn-secondary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/pages/update_text_block.turbo_stream.erb
<%= turbo_stream.update "flash", partial: "admin/shared/flash" %>