config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get "/:locale" => "pages#home"
    root to: "pages#home"

    get "about", to: "pages#about"
    resources :partners, only: %i[index]
    resources :projects, only: %i[index show]
    resources :messages, only: %i[new create]
  end

  namespace :admin do
    root to: "projects#index"

    resources :pages, only: %i[index edit] do
      resources :text_block, only: [] do
        member do
          patch :update_text_block, controller: "pages"
        end
      end
    end
    resources :project_categories, only: %i[index edit update] do
      member do
        get :update_position
      end
    end
    resources :projects, only: %i[index new create show edit update destroy] do
      resources :container_blocks, only: %i[create update destroy] do
        member do
          get :update_position
        end
        resources :content_blocks, only: [] do
          resources :text_blocks, only: %i[create update destroy]
          resources :image_blocks, only: %i[create update destroy]
          member do
            get :update_position
          end
        end
      end
    end
    resources :team_members, only: %i[index new create edit update destroy]
    resources :partners, only: %i[index new create edit update destroy]
    resources :messages, only: %i[index show destroy]
    resources :users, only: %i[index edit update]
  end
end

app/views/shared/_admin_sidebar.html.erb
<aside class="w-60 px-6 py-8 min-h-screen bg-black flex flex-col gap-10">
  <%= link_to root_path, class: "flex justify-center" do %>
    <%= image_tag "logo.png", class: "w-24" %>
  <% end %>
  <%=
    link_to root_path,
    class: "p-3 text-stone-300 border border-white border-dashed rounded transition-colors hover:bg-slate-900 ",
    target: :_blank do
  %>
    <div class="flex justify-between items-center">
      <span class="font-bold">Amerma</span>
      <%= inline_svg_tag("icons/arrow-top-right-on-square.svg", class: "w-5 shrink-0") %>
    </div>
    <span class="text-xs"><%= root_url %></span>
  <% end %>
  <div class="flex flex-col gap-1">
    <%= sidebar_link(t("projects"), admin_projects_path) %>
    <%= sidebar_link(t("projects_categories"), admin_project_categories_path) %>
    <%= sidebar_link(t("team_members"), admin_team_members_path) %>
    <%= sidebar_link(t("partners"), admin_partners_path) %>
    <%= sidebar_link(t("contact"), "#") %>
  </div>
</aside>

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="w-full fixed bottom-0 left-0 flex justify-center" data-controller="flash">
    <% if flash_type == "error" %>
      <div class="flex justify-center items-center gap-4 shadow-border bg-gray-500 text-white m-10 lg:w-1/2">
        <div class="grow flex justify-center items-center gap-4 p-5">
          <%= inline_svg_tag "icons/warning.svg", class: "shrink-0 w-8 h-8 fill-white hidden sm:block" %>
          <%= message %>
        </div>
        <div class="p-5 cursor-pointer hover:text-gray-300" data-action="click->flash#remove">
          <%= inline_svg_tag("icons/x-mark.svg", class: "w-8") %>
        </div>
      </div>
    <% else %>
      <div class="flex justify-center items-center gap-4 shadow-border bg-white m-10 lg:w-1/2">
        <div class="grow flex justify-center items-center gap-4 p-5">
          <%= inline_svg_tag "icons/happy-computer.svg", class: "shrink-0 w-8 h-8 fill-white hidden sm:block" %>
          <%= message %>
        </div>
        <div class="p-5 cursor-pointer hover:text-gray-800" data-action="click->flash#remove">
          <%= inline_svg_tag("icons/x-mark.svg", class: "w-8") %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-black py-10 text-white">
  <div class="container mx-auto px-6 sm:px-10 lg:px-24 xl:max-w-[1280px] flex justify-between items-center">
    <p>
      <% I18n.available_locales.sort { |a, b| b <=> a }.each do |locale| %>
          <% if locale.to_s == params[:locale] || (params[:locale].blank? && locale == I18n.default_locale)  %>
            <span class="bg-white text-black p-2"><%= locale.upcase %></span>
          <% else %>
            <%=
              link_to locale.upcase,
              params[:action] == "home" ? root_path(locale: locale) : url_for(locale: locale),
              class: "p-2 underline hover:no-underline"
            %>
          <% end %>
      <% end %>
    </p>
    <p class="flex gap-2 items-end">
      <span>
        <%= t("crafted_by") %> <%= link_to "renodor", "https://www.renodor.co", target: :_blank, class: "underline hover:no-underline" %>
      </span>
      <%= inline_svg_tag("icons/happy-computer.svg", class: "w-8 h-8 fill-white") %>
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="h-[56px] w-full text-white fixed top-0 z-10 group" data-controller="navbar" data-open="false">
  <div class="relative z-20 container px-6 py-2 mx-auto bg-black flex flex-nowrap justify-between items-center sm:px-10 lg:px-24 xl:max-w-[1280px]">
    <%= link_to root_path, class: "shrink-0" do %>
      <%= image_tag "logo.png", class: "w-32" %>
    <% end %>
    <div class="relative flex flex-col p-4 gap-1 cursor-pointer lg:hidden" data-action="click->navbar#toggleMobileNav">
      <div class="h-2 w-6"></div>
      <span
        class="absolute top-4 block w-6 h-0.5 bg-white group-[[data-open='true']]:top-[19px] group-[[data-open='true']]:rotate-45 group-[[data-open='false']]:[transition:top_0.1s_0.1s,transform_0.1s] group-[[data-open='true']]:[transition:top_0.1s,transform_0.1s_0.1s]"
      ></span>
      <span
        class="absolute top-[22px] block w-6 h-0.5 bg-white group-[[data-open='true']]:top-[19px] group-[[data-open='true']]:-rotate-45 group-[[data-open='false']]:[transition:top_0.1s_0.1s,transform_0.1s] group-[[data-open='true']]:[transition:top_0.1s,transform_0.1s_0.1s]"
      ></span>
    </div>
    <div class="hidden items-center justify-end lg:flex">
      <%= link_to about_path, class: "flex justify-end gap-1 px-1 py-2 group/item" do %>
        <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
        <span class="group-hover/item:underline"><%= t("who_are_we?") %></span>
        <span class="group-hover/item:translate-x-1 transition-transform">]</span>
      <% end %>
      <div class="relative group/item">
        <div class="absolute right-0 top-7 p-5 flex-col gap-4 text-right bg-black w-64 transition-all duration-200 invisible opacity-0 flex group-hover/item:visible group-hover/item:opacity-100 group-[[data-open='true']]:hidden">
          <% ProjectCategory.ordered.each do |project_category| %>
            <%= link_to translates(project_category, :name), projects_path(anchor: dom_id(project_category)), class: "hover:underline" %>
          <% end %>
        </div>
        <%= link_to projects_path, class: "relative flex justify-end gap-1 px-1 py-2" do %>
          <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
          <span class="group-hover/item:underline"><%= t("projects") %></span>
          <span class="group-hover/item:translate-x-1 transition-transform">]</span>
        <% end %>
      </div>
      <%= link_to partners_path, class: "flex justify-end gap-1 px-1 py-2 group/item" do %>
        <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
        <span class="group-hover/item:underline"><%= t("partners") %></span>
        <span class="group-hover/item:translate-x-1 transition-transform">]</span>
      <% end %>
      <%= link_to new_message_path, class: "flex justify-end gap-1 px-1 py-2 group/item" do %>
        <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
        <span class="group-hover/item:underline"><%= t("contact") %></span>
        <span class="group-hover/item:translate-x-1 transition-transform">]</span>
      <% end %>
    </div>
  </div>
  <div class="relative z-10 container mx-auto px-6 pb-4 w-full bg-black flex flex-col items-end sm:px-10 lg:hidden -translate-y-full transition-transform group-[[data-open='true']]:translate-y-0">
    <%= link_to about_path, class: "flex justify-end gap-1 p-1 group/item" do %>
      <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
      <span class="group-hover/item:underline"><%= t("who_are_we?") %></span>
      <span class="group-hover/item:translate-x-1 transition-transform">]</span>
    <% end %>
    <%= link_to projects_path, class: "flex justify-end gap-1 p-1 group/item" do %>
      <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
      <span class="group-hover/item:underline"><%= t("projects") %></span>
      <span class="group-hover/item:translate-x-1 transition-transform">]</span>
    <% end %>
    <%= link_to partners_path, class: "flex justify-end gap-1 p-1 group/item" do %>
      <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
      <span class="group-hover/item:underline"><%= t("partners") %></span>
      <span class="group-hover/item:translate-x-1 transition-transform">]</span>
    <% end %>
    <%= link_to new_message_path, class: "flex justify-end gap-1 p-1 group/item" do %>
      <span class="group-hover/item:-translate-x-1 transition-transform">[</span>
      <span class="group-hover/item:underline"><%= t("contact") %></span>
      <span class="group-hover/item:translate-x-1 transition-transform">]</span>
    <% end %>
  </div>
</nav>