config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get "/:locale" => "pages#home"
    root to: "pages#home"

    get "about", to: "pages#about"
    resources :partners, only: %i[index]
    resources :projects, only: %i[index show]
    resources :messages, only: %i[new create]
  end

  namespace :admin do
    root to: "projects#index"

    resources :pages, only: %i[index edit] do
      resources :text_block, only: [] do
        member do
          patch :update_text_block, controller: "pages"
        end
      end
    end
    resources :project_categories, only: %i[index edit update] do
      member do
        get :update_position
      end
    end
    resources :projects, only: %i[index new create show edit update destroy] do
      resources :container_blocks, only: %i[create update destroy] do
        member do
          get :update_position
        end
        resources :content_blocks, only: [] do
          resources :text_blocks, only: %i[create update destroy]
          resources :image_blocks, only: %i[create update destroy]
          member do
            get :update_position
          end
        end
      end
    end
    resources :team_members, only: %i[index new create edit update destroy]
    resources :partners, only: %i[index new create edit update destroy]
    resources :messages, only: %i[index show destroy]
    resources :users, only: %i[index edit update]
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :project_category
  has_many :container_blocks, -> { order(:position) }, as: :containerable, dependent: :destroy
  has_one_attached :cover_photo do |attachable|
    attachable.variant :square,
      preprocessed: true,  # TODO: as variant are preprocessed we could remove the original image to save space
      resize_to_fill: [96, 96],
      colorspace: :gray,
      format: "png",
      dither: "FloydSteinberg",
      colors: "6",
      saver: { strip: true }

    attachable.variant :cover,
      preprocessed: true, # TODO: as variant are preprocessed we could remove the original image to save space
      resize_to_fill: [1088, 176],
      colorspace: :gray,
      format: "png",
      dither: "FloydSteinberg",
      colors: "6",
      saver: { strip: true }

    # attachable.variant :cover,
    #   resize_to_fill: [1088, 176],
    #   colorspace: :gray,
    #   format: "png",
    #   ordered_dither: "o8x8"
  end

  scope :visible, -> { where(visible: true) }
  scope :featured, -> { where(featured: true) }

  validates :name, presence: true
  validate :cover_photo_type

  enum :status, {
    completed: 0,
    in_progress: 1,
    planned: 2
  }

  private

  def cover_photo_type
    return if cover_photo.blank? || %w[image/png image/jpeg image/webp image/gif].include?(cover_photo.content_type)

    errors.add :cover_photo, I18n.t("image_format_invalid")
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout "admin"

  def index
    @projects = Project.all.order(created_at: :desc)
  end

  def new
    @project_categories = ProjectCategory.all
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = t("project_created")
      redirect_to admin_project_path(@project)
    else
      @project_categories = ProjectCategory.all
      flash[:error] = t("project_create_error")
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @project_categories = ProjectCategory.all
    @project = Project.find(params[:id])
  end

  def edit
    @project_categories = ProjectCategory.all
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      @project.cover_photo.purge if params[:project][:remove_cover_photo]
      flash[:success] = t("project_updated")
      redirect_to admin_project_path(@project)
    else
      @project_categories = ProjectCategory.all
      flash.now[:error] = t("project_update_error")
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = t("project_deleted")
    redirect_to admin_projects_path
  end

  private

  def project_params
    params.require(:project).permit(
      :name, :name_en, :description, :description_en, :start_date, :end_date, :status, :project_category_id, :visible,
      :featured, :cover_photo, :owner
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @project_categories = ProjectCategory.ordered.includes(projects: [cover_photo_attachment: :blob])
  end

  def show
    @project = Project.find(params[:id])
    @container_blocks = @project.container_blocks.includes(
      content_blocks: [contentable: [:rich_text_text, :rich_text_text_en, image_attachment: :blob]]
    )

    redirect_to projects_path unless @project.visible?
  end
end

app/views/admin/projects/_form.html.erb
<section class="bg-white p-4 border">
  <%= form_with model: [:admin, project], class: "flex flex-col gap-4", multipart: true do |form| %>
    <div>
      <%=
        form.collection_select :project_category_id,
        project_categories,
        :id,
        :name,
        { include_blank: t("choose_category") },
        { class: "w-auto px-4 py-3 bg-white border" }
      %>
    </div>
    <div class="flex items-center gap-10">
      <div class="flex gap-4">
        <div>
          <%= form.label :visible_true, class: "flex flex-col items-center text-gray-400 px-4 py-1 border cursor-pointer has-[:checked]:bg-gray-100 has-[:checked]:text-black" do %>
            <%= form.radio_button :visible, true, class: "hidden" %>
            <%= t("visible") %>
            <%= inline_svg_tag("icons/eye-solid.svg", class: "w-4") %>
          <% end %>
        </div>
        <div>
          <%= form.label :visible_false, class: "flex flex-col items-center text-gray-400 px-4 py-1 border cursor-pointer has-[:checked]:bg-gray-100 has-[:checked]:text-black" do %>
            <%= form.radio_button :visible, false, class: "hidden" %>
            <%= t("hidden") %>
            <%= inline_svg_tag("icons/eye-slash.svg", class: "w-4") %>
          <% end %>
        </div>
      </div>
      <div class="flex gap-4">
        <div>
          <%= form.label :featured_true, class: "flex flex-col items-center text-gray-400 px-4 py-1 border cursor-pointer has-[:checked]:bg-gray-100 has-[:checked]:text-black" do %>
            <%= form.radio_button :featured, true, class: "hidden" %>
            <%= t("featured") %>
            <%= inline_svg_tag("icons/star-filled.svg", class: "w-4") %>
          <% end %>
        </div>
        <div>
          <%= form.label :featured_false, class: "flex flex-col items-center text-gray-400 px-4 py-1 border cursor-pointer has-[:checked]:bg-gray-100 has-[:checked]:text-black" do %>
            <%= form.radio_button :featured, false, class: "hidden" %>
            <%= t("not_featured") %>
            <%= inline_svg_tag("icons/star.svg", class: "w-4") %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="border p-3 relative">
      <%=
        render "admin/shared/image_upload",
        image: project.cover_photo,
        input_id: dom_id(project),
        variant_name: :cover,
        show_remove_button: true
      %>
    </div>
    <div class="flex gap-3">
      <div class="w-full">
        <%= form.label :name, "#{t("name")} FR" %>
        <%=
          form.text_field :name,
          placeholder: "#{t('name')}*",
          required: true,
          class: "w-full border p-3 font-bold text-xl"
        %>
      </div>
      <div class="w-full">
        <%= form.label :name_en, "#{t("name")} EN" %>
        <%=
          form.text_field :name_en,
          placeholder: "#{t('name')} EN",
          class: "w-full border p-3 font-bold text-xl"
        %>
      </div>
    </div>
    <div class="flex gap-4">
      <div>
        <%= form.label :status_completed, class: "flex flex-col items-center text-gray-400 px-4 py-1 border cursor-pointer has-[:checked]:bg-gray-100 has-[:checked]:text-black" do %>
          <%= form.radio_button :status, "completed", class: "hidden" %>
          <%= t("completed") %>
        <% end %>
      </div>
      <div>
        <%= form.label :status_in_progress, class: "flex flex-col items-center text-gray-400 px-4 py-1 border cursor-pointer has-[:checked]:bg-gray-100 has-[:checked]:text-black" do %>
          <%= form.radio_button :status, "in_progress", class: "hidden" %>
          <%= t("in_progress") %>
        <% end %>
      </div>
      <div>
        <%= form.label :status_planned, class: "flex flex-col items-center text-gray-400 px-4 py-1 border cursor-pointer has-[:checked]:bg-gray-100 has-[:checked]:text-black" do %>
          <%= form.radio_button :status, "planned", class: "hidden" %>
          <%= t("planned") %>
        <% end %>
      </div>
    </div>
    <div class="flex gap-6">
      <div>
        <%= form.label :start_date, t("start_date"), class: "text-sm" %>
        <%=
          form.date_field :start_date,
          class: "border p-3"
        %>
      </div>
      <div>
        <%= form.label :end_date, t("end_date"), class: "text-sm" %>
        <%=
          form.date_field :end_date,
          class: "border p-3"
        %>
      </div>
    </div>
    <%=
      form.text_field :owner,
      placeholder: t("owner"),
      class: "border p-3"
    %>
    <div>
      <%= form.label :description, "#{t("description")} FR" %>
      <%=
        form.textarea :description,
        placeholder: t("description"),
        class: "w-full border p-3"
      %>
    </div>
    <div>
      <%= form.label :description_en, "#{t("description")} EN" %>
      <%=
        form.textarea :description_en,
        placeholder: "#{t("description")} EN",
        class: "w-full border p-3"
      %>
    </div>

    <%= form.submit t("save"), class: "admin-btn-primary cursor-pointer" %>
  <% end %>
</section>

app/views/admin/projects/_project.html.erb
<section class="flex flex-col gap-4 bg-white p-4 border" data-spec="project-<%= project.id %>">
  <div class="flex items-center gap-10">
    <span class="px-4 py-3 bg-white border" data-spec="project-category">
      <%= project.project_category.name %>
    </span>
    <div class="flex flex-col items-center px-4 py-1 border bg-slate-100 text-slate-800" data-spec="project-visibility">
      <% if project.visible? %>
        <%= t("visible") %>
        <%= inline_svg_tag("icons/eye-solid.svg", class: "w-4") %>
      <% else %>
        <%= t("hidden") %>
        <%= inline_svg_tag("icons/eye-slash.svg", class: "w-4") %>
      <% end %>
    </div>
    <div class="flex flex-col items-center px-4 py-1 border bg-slate-100 text-slate-800" data-spec="project-featured">
      <% if project.featured? %>
        <%= t("featured") %>
        <%= inline_svg_tag("icons/star-filled.svg", class: "w-4") %>
      <% else %>
        <%= t("not_featured") %>
        <%= inline_svg_tag("icons/star.svg", class: "w-4") %>
      <% end %>
    </div>
  </div>

  <%= render "projects/header", project: project %>

  <div class="flex justify-end">
    <%= link_to t("edit"), edit_admin_project_path(project), class: "admin-btn-secondary text-sm px-3 py-1" %>
  </div>
</section>

app/views/admin/projects/edit.html.erb
<div class="flex justify-between items-center mb-6">
  <h2 class="text-2xl font-bold mb-4"><%= t("edit") %> <%= @project.name %></h2>
  <div class="flex gap-4">
    <%= link_to project_path(@project), target: :_blank, class: "admin-btn-secondary flex items-center gap-3", data: { spec: "project-link" } do %>
      <span><%= t("view_project") %></span>
      <%= inline_svg_tag "icons/outside.svg", class: "w-4 h-4" %>
    <% end %>
    <%=
      button_to t("delete"),
      admin_project_path(@project),
      data: { turbo_confirm: "Are you sure?", spec: "delete-project" },
      method: :delete,
      class: "admin-btn-delete"
    %>
  </div>
</div>

<%= render "form", project: @project, project_categories: @project_categories %>

app/views/admin/projects/index.html.erb
<header class="flex justify-between items-center mb-6">
  <h1 class="text-3xl font-bold mb-4"><%= t("projects") %></h1>
  <%= link_to t("new_project"), new_admin_project_path, class: "admin-btn-primary" %>
</header>
<div class="flex flex-col gap-4">
  <% @projects.each do |project| %>
    <div class="flex gap-4 items-center justify-between bg-white p-4 border" data-spec="project-<%= project.id %>">
      <div class="flex gap-4 items-center">
        <% if project.cover_photo.attached? %>
          <%= image_tag project.cover_photo.variant(:square), class: "object-cover shrink-0", data: { spec: "project-cover-photo" } %>
        <% end %>
        <div>
          <h2 class="text-xl font-bold" data-spec="project-name"><%= project.name %></h2>
          <p class="text-gray-500" data-spec="project-description"><%= project.description %></p>
        </div>
      </div>
      <div class="flex flex-col gap-4">
        <%= link_to t("manage"), admin_project_path(project), class: "admin-btn-secondary" %>
        <%=
          button_to(
            t("delete"),
            admin_project_path(project),
            method: :delete,
            data: { turbo_confirm: "Are you sure?" },
            class: "admin-btn-delete",
            form: { data: { spec: "delete-project"}}
          )
        %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/projects/new.html.erb
<div class="flex justify-between items-center mb-6">
  <h1 class="text-2xl font-bold mb-4"><%= t("new_project") %></h1>
</div>


<%= render "form", project: @project, project_categories: @project_categories %>

app/views/admin/projects/show.html.erb
<div class="flex justify-between items-center mb-6">
  <h2 class="text-2xl font-bold mb-4"><%= @project.name %></h2>
  <div class="flex gap-4">
    <%= link_to project_path(@project), target: :_blank, class: "admin-btn-secondary flex items-center gap-3", data: { spec: "project-link" } do %>
      <span><%= t("view_project") %></span>
      <%= inline_svg_tag "icons/outside.svg", class: "w-4 h-4" %>
    <% end %>
    <%=
      button_to t("delete"),
      admin_project_path(@project),
      data: { turbo_confirm: "Are you sure?", spec: "delete-project" },
      method: :delete,
      class: "admin-btn-delete"
    %>
  </div>
</div>

<div class="flex flex-col gap-4">
  <%= render @project %>

  <div id="<%= dom_id(@project, :container_blocks) %>" class="flex flex-col gap-4" data-spec="container-blocks">
    <%= render @project.container_blocks, project: @project %>
  </div>

  <div data-controller="modal">
    <%=
      button_tag type: :button,
      class: "admin-btn-secondary",
      data: { action: "click->modal#showModal" } do
    %>
      <%= inline_svg_tag("icons/plus.svg", class: "w-5") %>
      <span><%= t("container") %></span>
    <% end %>

    <dialog class="backdrop:bg-black/60 p-4" data-modal-target="dialog">
      <div class="flex flex-col gap-4">
        <div class="flex items-center">
          <h3 class="grow font-bold"><%= t("new_container") %></h3>
          <button data-action="click->modal#closeModal">
            <%= inline_svg_tag("icons/x-mark.svg", class: "w-6 text-black hover:opacity-70") %>
          </button>
        </div>
        <%=
          render "admin/container_blocks/form",
          container_block: ContainerBlock.new(
            class_list: ["grid", "gap-6", "items-center", "p-4", "border-none"],
            column_count: 1,
            position: @project.container_blocks.last&.position.to_i + 1
          ),
          project: @project
        %>
      </div>
    </dialog>
  </div>
</div>

app/views/admin/projects/update.turbo_stream.erb
<%= turbo_stream.update @project do %>
  <%= render @project %>
<% end %>

<%= turbo_stream.update "flash", partial: "admin/shared/flash" %>